language: generic

services:
  - docker

before_install:
    - docker build -t  sashamv/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true sashamv/react-test npm test -- --coverage

after_success:
    - docker build -t jamss/multi-client ./client
    - docker build -t jamss/multi-nginx ./nginx
    - docker build -t jamss/multi-server ./server
    - docker build -t jamss/multi-worker ./worker

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    - docker push jamss/multi-client
    - docker push jamss/multi-nginx
    - docker push jamss/multi-server
    - docker push jamss/multi-worker